src/Entity/RatholeService.php
<?php

namespace App\Entity;

use App\Repository\RatholeServiceRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RatholeServiceRepository::class)]
#[ORM\HasLifecycleCallbacks]
class RatholeService
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $token = null;

    #[ORM\ManyToOne(inversedBy: 'ratholeServices')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\Column(unique: true)]
    private ?int $bind_addr_port = 0;

    #[ORM\Column(length: 20)]
    private ?string $local_addr_ip = null;

    #[ORM\Column]
    private ?int $local_addr_port = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): static
    {
        $this->token = $token;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function getBindAddrPort(): ?int
    {
        return $this->bind_addr_port;
    }

    public function setBindAddrPort(?int $bind_addr_port): void
    {
        $this->bind_addr_port = $bind_addr_port;
    }

    public function getLocalAddrPort(): ?int
    {
        return $this->local_addr_port;
    }

    public function setLocalAddrPort(?int $local_addr_port): void
    {
        $this->local_addr_port = $local_addr_port;
    }

    public function getLocalAddrIP(): ?string
    {
        return $this->local_addr_ip;
    }

    public function setLocalAddrIP(?string $local_addr_ip): void
    {
        $this->local_addr_ip = $local_addr_ip;
    }

}

src/Form/RatholeServiceType.php
<?php

namespace App\Form;

use App\Entity\RatholeService;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RatholeServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('local_addr_ip')
            ->add('local_addr_port')
            ->add('active')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => RatholeService::class,
        ]);
    }
}

src/Controller/RatholeServiceController.php
<?php

namespace App\Controller;

use App\Entity\AppConfiguration;
use App\Entity\RatholeService;
use App\Form\RatholeServiceType;
use App\Repository\RatholeServiceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/service')]
class RatholeServiceController extends AbstractController
{
    /**
     * @var \App\Entity\AppConfiguration
     */
    private AppConfiguration $appConfig;

    public function __construct()
    {
        $this->appConfig = new AppConfiguration();
    }
    #[Route('/', name: 'app_rathole_service_index', methods: ['GET'])]
    public function index(RatholeServiceRepository $ratholeServiceRepository): Response
    {
        if (in_array('ROLE_ADMIN', $this->getUser()->getRoles())){
            $services = $ratholeServiceRepository->findAll();
        }
        else {
            $services = $ratholeServiceRepository->findBy(['user' => $this->getUser()]);
        }

        return $this->render('rathole_service/index.html.twig', [
            'rathole_services' => $services,
            'server_url' => $this->appConfig->getRatholeServerUrl(),
        ]);
    }

    /**
     * @throws \Exception
     */
    #[Route('/new', name: 'app_rathole_service_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        /** @var \App\Entity\User $user */
        $user = $this->getUser();
        if ($user->getRatholeServices()->count() >= $this->appConfig->getRatholeServerServicesLimit()){
            return new Response('Sorry, you cannot create more services', Response::HTTP_SERVICE_UNAVAILABLE);
        }

        $ratholeService = new RatholeService();
        $ratholeService->setToken(hash("sha256", (string) rand()));
        $ratholeService->setActive(true);
        $form = $this->createForm(RatholeServiceType::class, $ratholeService);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ratholeService->setBindAddrPort($this->getNextAvailablePort($entityManager));
            $ratholeService->setUser($user);
            $entityManager->persist($ratholeService);
            $entityManager->flush();

            return $this->redirectToRoute('app_rathole_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('rathole_service/new.html.twig', [
            'rathole_service' => $ratholeService,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_rathole_service_show', methods: ['GET'])]
    #[IsGranted('rathole_service_owner', 'ratholeService')]
    public function show(RatholeService $ratholeService): Response
    {
        return $this->render('rathole_service/show.html.twig', [
            'rathole_service' => $ratholeService,
            'server_url' => $this->appConfig->getRatholeServerUrl(),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_rathole_service_edit', methods: ['GET', 'POST'])]
    #[IsGranted('rathole_service_owner', 'ratholeService')]
    public function edit(Request $request, RatholeService $ratholeService, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RatholeServiceType::class, $ratholeService);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_rathole_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('rathole_service/edit.html.twig', [
            'rathole_service' => $ratholeService,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_rathole_service_delete', methods: ['POST'])]
    #[IsGranted('rathole_service_owner', 'ratholeService')]
    public function delete(Request $request, RatholeService $ratholeService, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid(
          'delete'.$ratholeService->getId(),
          (string)$request->request->get('_token')
        )) {
            $entityManager->remove($ratholeService);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_rathole_service_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @throws \Exception
     */
    private function getNextAvailablePort(EntityManagerInterface $entityManager): mixed
    {
        /** @var RatholeServiceRepository $serviceRepository */
        $serviceRepository = $entityManager->getRepository(RatholeService::class);
        $portsInUse = $serviceRepository->getAllPortsInUse();
        $availablePorts = array_diff($this->getAllPorts(), $portsInUse);

        if (count($availablePorts) >= 1) {
            return reset($availablePorts);
        }

        throw new \Exception('No available ports');
    }

    /**
     * @return array<int>
     */
    private function getAllPorts(): array
    {
        $data = [];
        for (
          $i = $this->appConfig->getMinPortRange();
          $i <= $this->appConfig->getMaxPortRange();
          $i++
        ) {
            $data[] = $i;
        }

        return $data;
    }
}

templates/rathole_service/_delete_form.html.twig
<form method="post" action="{{ path('app_rathole_service_delete', {'id': rathole_service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rathole_service.id) }}">
    <button class="btn">Delete</button>
</form>

templates/rathole_service/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/rathole_service/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RatholeService{% endblock %}

{% block body %}
    <h1>Edit RatholeService</h1>

    {{ include('rathole_service/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_rathole_service_index') }}">back to list</a>

    {{ include('rathole_service/_delete_form.html.twig') }}
{% endblock %}

templates/rathole_service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rathole Services{% endblock %}

{% block body %}
    <h1>Services:</h1>

    <div>
        <table>
            <thead>
            <tr>
                <th>Name</th>
                <th>Local IP</th>
                <th>Local port</th>
                <th>Public access at</th>
                <th>Active</th>
                {% if is_granted('ROLE_ADMIN') %}
                    <th>User</th>
                {% endif %}
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for rathole_service in rathole_services %}
                <tr>
                    <td>{{ rathole_service.name }}</td>
                    <td>{{ rathole_service.localAddrIP }}</td>
                    <td>{{ rathole_service.localAddrPort }}</td>
                    <td>{{ server_url }}:{{ rathole_service.bindAddrPort }}</td>
                    <td>{{ rathole_service.active ? 'Yes' : 'No' }}</td>
                    {% if is_granted('ROLE_ADMIN') %}
                        <td>{{ rathole_service.user }}</td>
                    {% endif %}
                    <td>
                        <a href="{{ path('app_rathole_service_show', {'id': rathole_service.id}) }}">show</a>
                        <a href="{{ path('app_rathole_service_edit', {'id': rathole_service.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_rathole_service_new') }}">Create new</a>
    </div>
{% endblock %}

templates/rathole_service/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New RatholeService{% endblock %}

{% block body %}
    <h1>Create new Service</h1>

    {{ include('rathole_service/_form.html.twig') }}

    <a href="{{ path('app_rathole_service_index') }}">back to list</a>
{% endblock %}

templates/rathole_service/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Service{% endblock %}

{% block body %}
    <h1>Service</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ rathole_service.name }}</td>
            </tr>
            <tr>
                <th>Local IP</th>
                <td>{{ rathole_service.localAddrIP }}</td>
            </tr>
            <tr>
                <th>Local port</th>
                <td>{{ rathole_service.localAddrPort }}</td>
            </tr>
            <tr>
                <th>Server port</th>
                <td>{{ rathole_service.bindAddrPort }}</td>
            </tr>
            <tr>
                <th>Token</th>
                <td>{{ rathole_service.token }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ rathole_service.active ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <p>
        Access to this service at {{ server_url }}:{{ rathole_service.bindAddrPort }}
    </p>

    <a href="{{ path('app_rathole_service_index') }}">back to list</a>

    <a href="{{ path('app_rathole_service_edit', {'id': rathole_service.id}) }}">edit</a>

    {{ include('rathole_service/_delete_form.html.twig') }}
{% endblock %}